### ISSUE TITLE
프론트 화면 만들기

### ISSUE THREAD

**Issue by choboss00** [choboss00/jump-to-spring-boot#6]
## Summary
백엔드 API 에 맞게 프론트 화면 설계하기

## TO-DO
- [ ] 메인 화면 만들기
- [ ] 로그인 화면 만들기
- [ ] 게시글 등록 화면 만들기
- [ ] 게시글 수정 화면 만들기
